##Pandas DataFrame And Series

Pandas is a powerful data manipulation library in Python, widely used for data analysis and data cleaning. It provides two primary data structures: Series and DataFrame. A Series is a one-dimensional array-like object, while a DataFrame is a two-dimensional, size-mutable, and potentially heterogeneous tabular data structure with labeled axes (rows and columns).

In [1]:
pip install pandas

Requirement already satisfied: pandas in c:\Users\HP\AppData\Local\Programs\Python\Python313\Lib\site-packages (3.0.3)
Requirement already satisfied: numpy>=1.26.0 in c:\Users\HP\AppData\Local\Programs\Python\Python313\Lib\site-packages (from pandas) (2.4.6)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\Users\HP\AppData\Local\Programs\Python\Python313\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\Users\HP\AppData\Local\Programs\Python\Python313\Lib\site-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in c:\Users\HP\AppData\Local\Programs\Python\Python313\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 26.0.1 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [3]:
import pandas as pd
## Series
## A Pandas Series is a one-dimensional array-like object that can hold any data type.
## It is similar to a NumPy array but with labeled indices.

import pandas as pd

data = [1, 2, 3, 4, 5]

series = pd.Series(data)

print("Series \n", series)

Series
 0    1
1    2
2    3
3    4
4    5
dtype: int64

In [4]:
# Create a Series from dictionary

data = {'a': 1, 'b': 2, 'c': 3}

series_dict = pd.Series(data)

print(series_dict)

a    1
b    2
c    3
dtype: int64

In [5]:
# Create a Series with custom index

data = [10, 20, 30]
index = ['a', 'b', 'c']

series = pd.Series(data, index=index)

print(series)

a    10
b    20
c    30
dtype: int64

In [6]:
## DataFrame
## Create a DataFrame from a dictionary of lists

import pandas as pd

data = {
    'Name': ['Krish', 'John', 'Jack'],
    'Age': [25, 30, 45],
    'City': ['Bangalore', 'New York', 'Florida']
}

df = pd.DataFrame(data)

print(df)

    Name  Age       City
0  Krish   25  Bangalore
1   John   30   New York
2   Jack   45    Florida

In [7]:
## Create a DataFrame From a List of Dictionaries

import pandas as pd

data = [
    {'Name': 'Krish', 'Age': 32, 'City': 'Bangalore'},
    {'Name': 'John', 'Age': 34, 'City': 'Bangalore'},
    {'Name': 'Bappy', 'Age': 32, 'City': 'Bangalore'},
    {'Name': 'JAck', 'Age': 32, 'City': 'Bangalore'}
]

df = pd.DataFrame(data)

print(df)
print(type(df))

    Name  Age       City
0  Krish   32  Bangalore
1   John   34  Bangalore
2  Bappy   32  Bangalore
3   JAck   32  Bangalore
<class 'pandas.DataFrame'>

In [8]:
df

    Name  Age       City
0  Krish   32  Bangalore
1   John   34  Bangalore
2  Bappy   32  Bangalore
3   JAck   32  Bangalore

In [9]:
df['Name']

0    Krish
1     John
2    Bappy
3     JAck
Name: Name, dtype: str

In [15]:
df.loc[0]## accessing to value through row

Name        Krish
Age            32
City    Bangalore
Name: 0, dtype: object

In [13]:
df.iloc[0]

Name        Krish
Age            32
City    Bangalore
Name: 0, dtype: object

In Pandas, **`loc`** and **`iloc`** are both used to select rows and columns, but they differ in how they identify data.

| Feature        | `loc`                             | `iloc`                             |
| -------------- | --------------------------------- | ---------------------------------- |
| Selection type | Label-based                       | Integer position-based             |
| Uses           | Row/column names (labels)         | Row/column indexes (0,1,2,...)     |
| End index      | Inclusive                         | Exclusive                          |
| Syntax         | `df.loc[row_label, column_label]` | `df.iloc[row_index, column_index]` |

### Example DataFrame

```python
import pandas as pd

data = {
    'Name': ['Krish', 'John', 'Jack'],
    'Age': [25, 30, 45],
    'City': ['Bangalore', 'New York', 'Florida']
}

df = pd.DataFrame(data)

print(df)
```

Output:

```text
    Name  Age       City
0  Krish   25  Bangalore
1   John   30   New York
2   Jack   45    Florida
```

---

## Using `loc`

Select by **label**:

```python
print(df.loc[0])
```

Output:

```text
Name         Krish
Age             25
City     Bangalore
```

Select specific row and column:

```python
print(df.loc[1, 'Name'])
```

Output:

```text
John
```

Multiple rows and columns:

```python
print(df.loc[0:1, ['Name', 'Age']])
```

Output:

```text
    Name  Age
0  Krish   25
1   John   30
```

Notice that `0:1` includes both rows **0 and 1**.

---

## Using `iloc`

Select by **position**:

```python
print(df.iloc[0])
```

Output:

```text
Name         Krish
Age             25
City     Bangalore
```

Select specific row and column:

```python
print(df.iloc[1, 0])
```

Output:

```text
John
```

Multiple rows and columns:

```python
print(df.iloc[0:2, 0:2])
```

Output:

```text
    Name  Age
0  Krish   25
1   John   30
```

Notice that `0:2` includes rows **0 and 1** but excludes row **2**.

---

## When Custom Indexes Exist

```python
df.index = ['a', 'b', 'c']
print(df)
```

Output:

```text
    Name  Age       City
a  Krish   25  Bangalore
b   John   30   New York
c   Jack   45    Florida
```

### `loc` uses labels

```python
df.loc['b']
```

Returns row with label `'b'`.

### `iloc` uses positions

```python
df.iloc[1]
```

Returns the second row (John).

---

### Quick Rule

* Use **`loc`** when you know the **row/column names**.
* Use **`iloc`** when you know the **row/column positions**.

A common interview question:

```python
df.loc[0:2]   # returns rows 0,1,2
df.iloc[0:2]  # returns rows 0,1
```

The key difference is that **`loc` includes the ending index, while `iloc` excludes it**.

In [16]:
## Accessing a specified element 
df.at[2,'Age']

np.int64(32)

In [17]:
df.iat[2,2]

'Bangalore'

In [22]:

import pandas as pd

data = [
    {'Name': 'Krish', 'Age': 32, 'City': 'Bangalore'},
    {'Name': 'John', 'Age': 34, 'City': 'Bangalore'},
    {'Name': 'Bappy', 'Age': 32, 'City': 'Bangalore'},
    {'Name': 'JAck', 'Age': 32, 'City': 'Bangalore'}
]

df = pd.DataFrame(data)

print(df)
print(type(df))
df['Salary']=[50000,60000,70000,80000]
df

    Name  Age       City
0  Krish   32  Bangalore
1   John   34  Bangalore
2  Bappy   32  Bangalore
3   JAck   32  Bangalore
<class 'pandas.DataFrame'>

    Name  Age       City  Salary
0  Krish   32  Bangalore   50000
1   John   34  Bangalore   60000
2  Bappy   32  Bangalore   70000
3   JAck   32  Bangalore   80000

In [33]:
if 'Salary' in df.columns:
    df = df.drop(columns=['Salary'])
else:
    print("Salary column not found")

Salary column not found

In [32]:
df

    Name  Age       City
0  Krish   32  Bangalore
1   John   34  Bangalore
2  Bappy   32  Bangalore
3   JAck   32  Bangalore

In [34]:
df

    Name  Age       City
0  Krish   32  Bangalore
1   John   34  Bangalore
2  Bappy   32  Bangalore
3   JAck   32  Bangalore

In [43]:
df['Age']=df['Age']+1
df

    Name  Age       City
0  Krish   40  Bangalore
1   John   42  Bangalore
2  Bappy   40  Bangalore
3   JAck   40  Bangalore

In [45]:
df.drop(0,inplace=True)
df

KeyError: '[0] not found in axis'

In [47]:
print(df.index)
df

RangeIndex(start=1, stop=4, step=1)

    Name  Age       City
1   John   42  Bangalore
2  Bappy   40  Bangalore
3   JAck   40  Bangalore

In [48]:
df.drop(1,inplace=True)
df

    Name  Age       City
2  Bappy   40  Bangalore
3   JAck   40  Bangalore

In [49]:
df.describe()

        Age
count   2.0
mean   40.0
std     0.0
min    40.0
25%    40.0
50%    40.0
75%    40.0
max    40.0

In [50]:
df.dtypes

Name      str
Age     int64
City      str
dtype: object

In [51]:
## Handling Missing Value
df.isnull()

    Name    Age   City
2  False  False  False
3  False  False  False

In [52]:
df.isnull().any(axis=1)

2    False
3    False
dtype: bool

In [53]:
df.isnull().sum()

Name    0
Age     0
City    0
dtype: int64

In [54]:
df.fillna(0)

    Name  Age       City
2  Bappy   40  Bangalore
3   JAck   40  Bangalore

In [ ]:
df['Sales_fillna']=df['Age'].fillna(df['Age'].mean())## Fill the missing value with mean of Age 
df

    Name  Age       City  Sales_fillna
2  Bappy   40  Bangalore            40
3   JAck   40  Bangalore            40

In [60]:
## Rename the column name
df=df.rename(columns={'Age':'Age of Number'})
df

    Name  Age of Number       City  Sales_fillna
2  Bappy             40  Bangalore            40
3   JAck             40  Bangalore            40

In [61]:
## Change the datatype

df['Age of Number1']=df['Age of Number'].astype(int)

In [63]:
df['Age of Number square']=df['Age of Number'].apply(lambda x:x**2)
df

,Name,Age of Number,City,Sales_fillna,Age of Number1,Age of Number square
2,Bappy,40,Bangalore,40,40,1600
3,JAck,40,Bangalore,40,40,1600

In [65]:
group_mean=df.groupby('Name')['Age of Number'].mean()
print(group_mean)

Name
Bappy    40.0
JAck     40.0
Name: Age of Number, dtype: float64

In [66]:
df.groupby(['Name','City'])['Age of Number'].sum()

Name   City
Bappy  Bangalore    40
JAck   Bangalore    40
Name: Age of Number, dtype: int64

In [69]:
group_arr=df.groupby('Name')['Age of Number'].agg(['mean','sum','count'])
group_arr

       mean  sum  count
Name
Bappy  40.0   40      1
JAck   40.0   40      1

In [73]:
### Merging and Joining DataFrames

# Create sample DataFrames

df1 = pd.DataFrame({
    'Key': ['A', 'B', 'C'],
    'Value1': [1, 2, 3]
})

df2 = pd.DataFrame({
    'Key': ['A', 'B', 'D'],
    'Value2': [4, 5, 6]
})
df1

  Key  Value1
0   A       1
1   B       2
2   C       3

In [74]:
df2

  Key  Value2
0   A       4
1   B       5
2   D       6

In [75]:
merged_df = pd.merge(df1, df2, on='Key',how='inner')

print(merged_df)

  Key  Value1  Value2
0   A       1       4
1   B       2       5

In [81]:
merged_df = pd.merge(df1, df2, on='Key',how='outer')

print(merged_df)

  Key  Value1  Value2
0   A     1.0     4.0
1   B     2.0     5.0
2   C     3.0     NaN
3   D     NaN     6.0

In [82]:
import pandas as pd
from io import StringIO

Data = '''
{
    "employee_name": "James",
    "email": "james@gmail.com",
    "job_profile": [
        {
            "title1": "Team Lead",
            "title2": "Sr. Developer"
        }
    ]
}
'''

# Read JSON
df = pd.read_json(StringIO(Data))

# Flatten job_profile
job_df = pd.json_normalize(df['job_profile'][0])

print(job_df)

      title1         title2
0  Team Lead  Sr. Developer

In [83]:
df.to_json()

'{"employee_name":{"0":"James"},"email":{"0":"james@gmail.com"},"job_profile":{"0":{"title1":"Team Lead","title2":"Sr. Developer"}}}'

In [84]:
df.to_json(orient='index')

'{"0":{"employee_name":"James","email":"james@gmail.com","job_profile":{"title1":"Team Lead","title2":"Sr. Developer"}}}'

In [85]:
df.to_json(orient='records')

'[{"employee_name":"James","email":"james@gmail.com","job_profile":{"title1":"Team Lead","title2":"Sr. Developer"}}]'

In [ ]:
import pandas as pd

df = pd.read_csv(
    "https://archive.ics.uci.edu/ml/machine-learning-databases/wine/wine.data",
    header=None## Mean first row contain column name
)

In [87]:
df

,0,1,2,3,4,5,6,7,8,9,10,11,12,13
0,1,14.23,1.71,2.43,15.6,127,2.80,3.06,0.28,2.29,5.64,1.04,3.92,1065
1,1,13.20,1.78,2.14,11.2,100,2.65,2.76,0.26,1.28,4.38,1.05,3.40,1050
2,1,13.16,2.36,2.67,18.6,101,2.80,3.24,0.30,2.81,5.68,1.03,3.17,1185
3,1,14.37,1.95,2.50,16.8,113,3.85,3.49,0.24,2.18,7.80,0.86,3.45,1480
4,1,13.24,2.59,2.87,21.0,118,2.80,2.69,0.39,1.82,4.32,1.04,2.93,735
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
173,3,13.71,5.65,2.45,20.5,95,1.68,0.61,0.52,1.06,7.70,0.64,1.74,740
174,3,13.40,3.91,2.48,23.0,102,1.80,0.75,0.43,1.41,7.30,0.70,1.56,750
175,3,13.27,4.28,2.26,20.0,120,1.59,0.69,0.43,1.35,10.20,0.59,1.56,835
176,3,13.17,2.59,2.37,20.0,120,1.65,0.68,0.53,1.46,9.30,0.60,1.62,840
177,3,14.13,4.10,2.74,24.5,96,2.05,0.76,0.56,1.35,9.20,0.61,1.60,560

In [88]:
df.to_csv('wine.csv')

In [91]:
!pip install lxml

Requirement already satisfied: lxml in C:\Users\HP\AppData\Local\Programs\Python\Python313\Lib\site-packages (6.1.1)

[notice] A new release of pip is available: 26.0.1 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [98]:
import pandas as pd
import requests

url = "https://www.fdic.gov/bank/individual/failed/banklist.html"



tables = pd.read_html(url)
tables[0]

,Bank Name,City,State,Cert,Acquiring Institution,Closing Date,Fund Sort ascending
0,Community Bank and Trust - West Georgia,LaGrange,Georgia,25796,Anchor Bank,"May 1, 2026",10551
1,Metropolitan Capital Bank & Trust,Chicago,Illinois,57488,First Independence Bank,"January 30, 2026",10550
2,The Santa Anna National Bank,Santa Anna,Texas,5520,Coleman County State Bank,"June 27, 2025",10549
3,Pulaski Savings Bank,Chicago,Illinois,28611,Millennium Bank,"January 17, 2025",10548
4,The First National Bank of Lindsay,Lindsay,Oklahoma,4134,First Bank & Trust Co.,"October 18, 2024",10547
5,Republic First Bank dba Republic Bank,Philadelphia,Pennsylvania,27332,"Fulton Bank, National Association","April 26, 2024",10546
6,Citizens Bank,Sac City,Iowa,8758,Iowa Trust & Savings Bank,"November 3, 2023",10545
7,Heartland Tri-State Bank,Elkhart,Kansas,25851,"Dream First Bank, N.A.","July 28, 2023",10544
8,First Republic Bank,San Francisco,California,59017,"JPMorgan Chase Bank, N.A.","May 1, 2023",10543
9,Signature Bank,New York,New York,57053,"Flagstar Bank, N.A.","March 12, 2023",10540
10,Silicon Valley Bank,Santa Clara,California,24735,First–Citizens Bank & Trust Company,"March 10, 2023",10539
11,Almena State Bank,Almena,Kansas,15426,Equity Bank,"October 23, 2020",10538
12,First City Bank of Florida,Fort Walton Beach,Florida,16748,"United Fidelity Bank, fsb","October 16, 2020",10537
13,The First State Bank,Barboursville,West Virginia,14361,"MVB Bank, Inc.","April 3, 2020",10536
14,Ericson State Bank,Ericson,Nebraska,18265,Farmers and Merchants Bank,"February 14, 2020",10535
15,City National Bank of New Jersey,Newark,New Jersey,21111,Industrial Bank,"November 1, 2019",10534
16,Resolute Bank,Maumee,Ohio,58317,Buckeye State Bank,"October 25, 2019",10533
17,Louisa Community Bank,Louisa,Kentucky,58112,Kentucky Farmers Bank Corporation,"October 25, 2019",10532
18,The Enloe State Bank,Cooper,Texas,10716,"Legend Bank, N. A.","May 31, 2019",10531
19,Washington Federal Bank for Savings,Chicago,Illinois,30570,Royal Savings Bank,"December 15, 2017",10530
20,The Farmers and Merchants State Bank of Argonia,Argonia,Kansas,17719,Conway Bank,"October 13, 2017",10529
21,Fayette County Bank,Saint Elmo,Illinois,1802,"United Fidelity Bank, fsb","May 26, 2017",10528
22,"Guaranty Bank, (d/b/a BestBank in Georgia & Mi...",Milwaukee,Wisconsin,30003,First-Citizens Bank & Trust Company,"May 5, 2017",10527
23,First NBC Bank,New Orleans,Louisiana,58302,Whitney Bank,"April 28, 2017",10526
24,Proficio Bank,Cottonwood Heights,Utah,35495,Cache Valley Bank,"March 3, 2017",10525

In [ ]:
# import pandas as pd

# url = "https://en.wikipedia.org/wiki/Mobile_country_code"

# df = pd.read_html(
#     url,
#     match="Country",
#     header=0
# )[0]

# print(df.head())

HTTPError: HTTP Error 403: Forbidden

In [100]:
!pip install openpyxl

Requirement already satisfied: openpyxl in C:\Users\HP\AppData\Local\Programs\Python\Python313\Lib\site-packages (3.1.5)
Requirement already satisfied: et-xmlfile in C:\Users\HP\AppData\Local\Programs\Python\Python313\Lib\site-packages (from openpyxl) (2.0.0)

[notice] A new release of pip is available: 26.0.1 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [103]:
df=pd.read_excel('variant_dish.xlsx')
df

,dish_id,variant_dish_name,regional_alias_name,english_translated_name,region,state,city_or_district,community_identity,gi_tag,gi_tag_details,...,sourece_url,Unnamed: 20,Unnamed: 21,Unnamed: 22,Unnamed: 23,Unnamed: 24,Unnamed: 25,Unnamed: 26,Unnamed: 27,Unnamed: 28
0,CH-099,Amritsari Kulcha Hub Style Kulcha,Kulcha,Stuffed flatbread Chandigarh style,North India,Chandigarh,Sector 9,Punjabi,No,empty,...,https://wanderlog.com/list/geoCategory/1556274...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,CH-001,Methi Makki Di Roti,Makki Roti,Fenugreek Maize Flatbread,North India,Chandigarh,empty,Punjabi,No,empty,...,https://www.youtube.com/results?search_query=m...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,CH-002,Atta Pinni,Pinni,Wheat Flour Sweet Ball,North India,Chandigarh,empty,Punjabi,No,empty,...,https://www.vegrecipesofindia.com/pinni-recipe/,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,CH-002,Dry Fruit Pinni,Pinni,Dry Fruit Sweet Ball,North India,Chandigarh,empty,Punjabi,No,empty,...,https://www.archanaskitchen.com/dry-fruit-pinn...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,CH-003,Badam Patisa,Patisa,Almond Flaky Sweet,North India,Chandigarh,empty,Traditional Sweet Makers,No,empty,...,https://www.bikanervala.com/products/badam-patisa,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
690,UK-543-V2,Bhatt Rus,Black Soybean Rus,Black Soybean and Lentil Soup,North India,Uttarakhand,Bageshwar,Kumaoni,No,empty,...,https://www.euttaranchal.com/culture/rus.php,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
691,UK-544-V1,Palak Kapa,Spinach Kapa,Traditional Spinach Curry,North India,Uttarakhand,Chamoli,Garhwali,No,empty,...,https://cookwithrenu.com/palak-ka-kaapa-spinac...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
692,UK-545-V1,Gur Gulgula,Jaggery Gulgula,Sweet Fried Dumplings with Jaggery,North India,Uttarakhand,Dehradun,Garhwali,No,empty,...,https://www.facebook.com/Aashirvaad/posts/a-fa...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
693,UK-545-V2,Til Gulgula,Sesame Gulgula,Sweet Fried Dumplings with Sesame Seeds,North India,Uttarakhand,Dehradun,Garhwali,No,empty,...,https://en.wikipedia.org/wiki/Gulgula_(doughnut),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
694,UK-546,Sisunak Ka Kafuli,Nettle Leaf Kafuli,Stinging Nettle Thick Green Curry,North India,Uttarakhand,Uttarkashi,Garhwali,No,empty,...,https://www.goya.in/blog/a-stinging-nettle-saa...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN